# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTooltips' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTooltips
  pod 'SexyTooltip',:git => 'https://github.com/prscX/SexyTooltip.git', :commit =>'2fbe10260fb1b0f7dcd9822681a6970ce88112af'
  pod 'pop', '~> 1.0'
end
